### ISSUE TITLE
Popup Box showing and the bot stuck

### ISSUE THREAD

**Issue by camlogical** [KevinLage/Edu-Account-creator#10]
After bot click on street address, a popup box showing and it was stuck. How to fix this? I used py not exe. Can you show me the code to bypass it?

![Screenshot 2019-12-01 01 21 42](https://user-images.githubusercontent.com/57839516/69910330-6c8d1500-143c-11ea-902d-015d0f70ae51.png)

**Comment by KevinLage** [comment]
tested the .exe version. Worked fine

try to restart the bot

**Comment by KevinLage** [comment]
btw. which college did u used?

**Comment by camlogical** [comment]
Yes .exe work fine but I want to add some college that why I want to use .py from your source code. But it stuck Like screenshot above. can you help me in this point. 
Note: all college stuck in this popup box (py). 

![Untitled](https://user-images.githubusercontent.com/57839516/69914608-b1cf3800-1478-11ea-9b00-6752dfc9bcac.png)

**Comment by KevinLage** [comment]
.py works fine too

add me on discord Wolf#0284

**Comment by camlogical** [comment]
can you upload your update py file?

**Comment by KevinLage** [comment]
I changed nothing, the py file in the repo works

**Comment by camlogical** [comment]
I found the Problem. Because I changed DOB to 2001 that why this box start popup. Can you help me if I change DOB code to 2001 how to bypass this popup?
