### ISSUE TITLE
Not going forward

### ISSUE THREAD

**Issue by ghost** [KevinLage/Edu-Account-creator#13]
Hi
       I tried to generate 1 acc but it is opening 7-8 mozzila Firefox and crating only openccc acc it is not going to any edu site and filling details

**Comment by KevinLage** [comment]
make sure you have all files in the same folder

**Comment by ghost** [comment]
Yes buddy I have all cloned files in one folder

**Comment by camlogical** [comment]
> Yes buddy I have all cloned files in one folder

For me work fine. Perhaps you missed in some points.

**Comment by KevinLage** [comment]
are you using the .exe or the .py?

**Comment by ledzeppblues** [comment]
hello ,i apologize in advance but i am a complete fool when it comes to this ,can you please guide me how to use it as i open mozilla and geckodriver.exe and a blank cmd window opens up.

I apologize in advance but i have no clue on how to use it please 
Any guidance would be appreciated

**Comment by camlogical** [comment]
make sure you update your python to latest. install pip + install requirement of his script.

**Comment by ghost** [comment]
Oke l will try thank you!

**Comment by KevinLage** [comment]
add me on Discord if you still need help Wolf#0284
