### ISSUE TITLE
Don't save info after creating account

### ISSUE THREAD

**Issue by EJ20199** [KevinLage/Edu-Account-creator#17]
Hi Kevin, 
I have come up with a little issue, that the creator fail to save the information to file accountsb.txt as the previous version. Still running to the sleeping for 25 sec then open new browser.
BTW the San_Bernardino not accept tempr email anymore
![Annotation 2020-01-15 122325](https://user-images.githubusercontent.com/58543324/72407456-2db7e200-3792-11ea-9e40-cb3611210ae3.png)

**Comment by MrKinauJr** [comment]
works for me.

**Comment by EJ20199** [comment]
> 
> 
> works for me.

hi there, can i have your telegram ID? i have supplement 3 more college in the previous version, can you help me contribute to this new one?

**Comment by MrKinauJr** [comment]
mrkinaujr on telegram
