### ISSUE TITLE
no id is getting succeded

### ISSUE THREAD

**Issue by arjun4414** [KevinLage/Edu-Account-creator#19]
no id is getting succeded after making id on he creator the id is not getting success at all 

can you state which of the colleges are working for the edu drive?

**Comment by KevinLage** [comment]
you mean google drive?

**Comment by camlogical** [comment]
> you mean google drive?

Could you please tell us like which colleges working with your bot now. Because some colleges we got nothing.

**Comment by KevinLage** [comment]
Im using Gavilan College and it works great

**Comment by camlogical** [comment]
> Im using Gavilan College and it works great

Can you show me how many mail / what is mail that gavilan sent to you to make your progress successful ?

**Comment by KevinLage** [comment]
first you get this email
![grafik](https://user-images.githubusercontent.com/43577910/74154210-8902b600-4c12-11ea-8480-f009bc53755e.png)

after some hours you will receive this mail:
![grafik](https://user-images.githubusercontent.com/43577910/74154283-ae8fbf80-4c12-11ea-821e-ad783fbbcc4b.png)

**Comment by ghost** [comment]
also not working for me. how often do you change your ip? or do you always use the same ip. and wouldnt it better to use protonemail i think that they blacklisted tempr mail.

**Comment by KevinLage** [comment]
yeah it looks like they blacklisted tempr mail
you can use your own mail or custom Domain

**Comment by ghost** [comment]
thanks for the new update. changing the email domain worked :) you can close this issue. maybe is it possible to randomize the domain? maybe that helps to not getting it blacklisted so fast
