### ISSUE TITLE
The setup dont run

### ISSUE THREAD

**Issue by yalero** [KevinLage/Edu-Account-creator#20]
Wen I run the setup,  its open and close at the same time

**Comment by EJ20199** [comment]
> 
> 
> Wen I run the setup, its open and close at the same time

you need to install python and Vcrunner first, then install the request

**Comment by yalero** [comment]
yes I have python instaled but what is Vcrunner?? I am searching but I dont see nothing

**Comment by KevinLage** [comment]
you dont need Vcrunner

**Comment by KevinLage** [comment]
can you open the program in the cmd so you can show the error?

**Comment by KevinLage** [comment]
btw. you can use the exe from releases so you dont need any python modules

**Comment by yalero** [comment]
![Captura](https://user-images.githubusercontent.com/39531822/73600641-930e2000-4553-11ea-9d5c-ca134b48513c.PNG)
That is the error

**Comment by MrKinauJr** [comment]
`py -m pip install selenium --user` please put this into the cmd.

**Comment by yalero** [comment]
yes, that was, thx
