### ISSUE TITLE
Captcha is not completing in auto mode

### ISSUE THREAD

**Issue by johnpatrick9** [KevinLage/Edu-Account-creator#21]
Hello,whenever I try to run the exe program and select the auto captcha option,it seems to skip it and I have to manually solve the captcha,could you please fix this issue? @KevinLage

**Comment by EJ20199** [comment]
you need to input your 2Captcha API key in the config file

**Comment by johnpatrick9** [comment]
Ok and how add the api key? sorry I am quite new to this @EJ20199 would you mind helping me out?

**Comment by camlogical** [comment]
> Ok and how add the api key? sorry I am quite new to this @EJ20199 would you mind helping me out?

Buy credit in 2captcha website to get api key. If you are newbie just use manual captcha.

**Comment by johnpatrick9** [comment]
Oh ok sorry for the trouble
