### ISSUE TITLE
Open firefox browser repeatedly

### ISSUE THREAD

**Issue by sonlamit** [KevinLage/Edu-Account-creator#24]
Message: Unable to locate element: [id="hasOtherNameNo"]

list index out of range
![image](https://user-images.githubusercontent.com/61155957/74668642-3740c980-51d8-11ea-8d42-eb177723b248.png)

**Comment by sritub** [comment]
It reopens browsers when the script fails, can you please download my fork and try: https://github.com/sritub/Edu-Account-creator

**Comment by sonlamit** [comment]
I tried it the same way

**Comment by sritub** [comment]
Can you please share screenshot? Also please make sure you are not editing any part of script before running.

**Comment by sonlamit** [comment]
![image](https://user-images.githubusercontent.com/61155957/74716366-fa6ce500-5260-11ea-8191-932239d52cf9.png)
![image](https://user-images.githubusercontent.com/61155957/74716396-0b1d5b00-5261-11ea-99b5-f9710e36f66a.png)
![image](https://user-images.githubusercontent.com/61155957/74716414-13759600-5261-11ea-8c9b-3ea4ac7bd2b1.png)

**Comment by sritub** [comment]
Can you please try this?

Replace "Edu Bot.py" with this file https://gofile.io/?c=TPB7kL

**Comment by sonlamit** [comment]
Where do I get answer emails? @brunhilde.ml

**Comment by sritub** [comment]
Go to tempr.email and below input field, there's a drop-down, select that and select brunhilde.ml
