### ISSUE TITLE
How to login mail for xxx@brunhilde.ml

### ISSUE THREAD

**Issue by gerryhjs** [KevinLage/Edu-Account-creator#25]

**Comment by gerryhjs** [comment]
After I login, I found the brunhilde.ml is not used for email anymore now.

**Comment by ceelopez** [comment]
How do you login to the temporary email? The brunhilde.ml or is there a workaround for this?

**Comment by sritub** [comment]
You can change email domain in config.txt file.

**Comment by sritub** [comment]
You can login to email by visiting https://tempr.email

**Comment by gerryhjs** [comment]
I login by https://tempr.email but It said brunhilde.ml cannot recieve email anymore.

**Comment by sritub** [comment]
Yes, please change domain in config.txt file to something that works.
