### ISSUE TITLE
Check Accept or No?

### ISSUE THREAD

**Issue by IIMugi** [KevinLage/Edu-Account-creator#27]
Hello sir, i created one account with your bot. But where can i check it accept or not ? I entered openccc but i didnt found any detailed information about account.

**Comment by sritub** [comment]
You'll have to wait a few days for college to go through your application, log in to your temp mail and check regularly.

**Comment by IIMugi** [comment]
i created one week ago. How do i enter temp mail sir ? Which site i can enter my temp mail ?

**Comment by KevinLage** [comment]
temp.email

**Comment by IIMugi** [comment]
i think the site is not working anymore. can you check the picture https://prnt.sc/rfdb4h

**Comment by KevinLage** [comment]
https://tempr.email/

sorry

**Comment by IIMugi** [comment]
thanks for helping :) btw brunhilde wont be use after 21 march

**Comment by IIMugi** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/61661070/76539417-cc5e7780-6491-11ea-9b66-4bde6b220869.png)

**Comment by KevinLage** [comment]
okay thanks

**Comment by camlogical** [comment]
> thanks for helping :) btw brunhilde wont be use after 21 march

Use Gmail for better experience.

**Comment by ghost** [comment]
@KevinLage  Discord Check :)

**Comment by maomao1317** [comment]
This method still use brunhilde email, but the email can not use anymore. How to use my own email, please? Or can you fix this to use other emails?

**Comment by KevinLage** [comment]
just change the config file

**Comment by thuyhangk33hlu** [comment]
Hi KevinLage, Thanks for your great works!
Can your made a choose domain for temp email , because brunhilde domain not working anymore , and use own mail can do with 1 acc each time.
![image](https://user-images.githubusercontent.com/56870781/79188587-a722a780-7e49-11ea-9ae7-fe7d91e54889.png)

**Comment by thuyhangk33hlu** [comment]
Hi KevinLage, Thanks for your great works!
