### ISSUE TITLE
No college seems to be accepting the application!

### ISSUE THREAD

**Issue by UjjwalD77** [KevinLage/Edu-Account-creator#29]
No college seems to be accepting the application!
I tried this like 10-20 days ago tried many colleges but none of them replied. 

Did it work for anyone else?

**Comment by camlogical** [comment]
1. Use VPN that in the same state or nearby of school you're applying.
2. Use Gmail
you just wait 2 or 3days. Good luck

**Comment by TianjinChen1** [comment]
Do we need to put real ssn

**Comment by KevinLage** [comment]
no
