### ISSUE TITLE
It isn't working anymore 

### ISSUE THREAD

**Issue by rusteamer** [KevinLage/Edu-Account-creator#32]
Can I use the received mail somewhere? It looks like this is no longer working. No site accepts my mail: 

Sorry, we can't accept your email address because we are not able to identify if the people from this email domain are truly students or not.
This could have happened for the following reasons:

Your school allows registering an email address there even if you are not a student of the college.
Someone from the school sold or shared their account details or activation code publicly, which has led to a broad account misuse and license terms violation.
If you are a student of this college, please apply with an official document.

Is there at least one working option?

**Comment by KevinLage** [comment]
use your own gmail

**Comment by TianjinChen1** [comment]
> use your own gmail

maybe  add function randomly pick major.
That may help school accept the application.

**Comment by MdTalhaZubayer** [comment]
"list index out of range" problem help me, please
