### ISSUE TITLE
security questions-LOS RIOS

### ISSUE THREAD

**Issue by TianjinChen1** [KevinLage/Edu-Account-creator#33]
What school did you attend for sixth grade?
What is the first name of your least favorite relative?

what is the answer for those question.
This is require when I try to create password. 
Plz help.

**Comment by owinrojas** [comment]
read the source
` 
   input_security1.click()
    input_answer1 = WebDriverWait(driver, 60).until(
        EC.presence_of_element_located((By.ID, 'inputSecurityAnswer1'))
    )
    input_answer1.send_keys("12")

    input_security2 = WebDriverWait(driver, 60).until(
        EC.element_to_be_clickable(
            (By.CSS_SELECTOR, '#inputSecurityQuestion2 option[value="4"]'))
    )
    input_security2.click()
    input_answer2 = WebDriverWait(driver, 60).until(
        EC.presence_of_element_located((By.ID, 'inputSecurityAnswer2'))
    )
    input_answer2.send_keys("Josh")

    input_security3 = WebDriverWait(driver, 60).until(
        EC.element_to_be_clickable(
            (By.CSS_SELECTOR, '#inputSecurityQuestion3 option[value="2"]'))
    )
    input_security3.click()
    input_answer3 = WebDriverWait(driver, 60).until(
        EC.presence_of_element_located((By.ID, 'inputSecurityAnswer3'))
    )
    input_answer3.send_keys("Tesla 3")`
12, Josh, Tesla 3

**Comment by Nigel1992** [comment]
> read the source
> `
> input_security1.click()
> input_answer1 = WebDriverWait(driver, 60).until(
> EC.presence_of_element_located((By.ID, 'inputSecurityAnswer1'))
> )
> input_answer1.send_keys("12")
> 
> ```
> input_security2 = WebDriverWait(driver, 60).until(
>     EC.element_to_be_clickable(
>         (By.CSS_SELECTOR, '#inputSecurityQuestion2 option[value="4"]'))
> )
> input_security2.click()
> input_answer2 = WebDriverWait(driver, 60).until(
>     EC.presence_of_element_located((By.ID, 'inputSecurityAnswer2'))
> )
> input_answer2.send_keys("Josh")
> 
> input_security3 = WebDriverWait(driver, 60).until(
>     EC.element_to_be_clickable(
>         (By.CSS_SELECTOR, '#inputSecurityQuestion3 option[value="2"]'))
> )
> input_security3.click()
> input_answer3 = WebDriverWait(driver, 60).until(
>     EC.presence_of_element_located((By.ID, 'inputSecurityAnswer3'))
> )
> input_answer3.send_keys("Tesla 3")`
> ```
> 
> 12, Josh, Tesla 3

Those are for OpenCCC.
The questions @TianjinChen1 is looking for is: nulled [for both questions]
