### ISSUE TITLE
no module named requests

### ISSUE THREAD

**Issue by oriolluz** [KevinLage/Edu-Account-creator#35]
Traceback (most recent call last):
  File "EduBot.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by camlogical** [comment]
install Requests module:
`pip install requests`

**Comment by oriolluz** [comment]
it still doesent work it says all requerments satisfied

**Comment by camlogical** [comment]
> it still doesent work it says all requerments satisfied

Because you use 2 versions of pip,
follow here:
`pip install requests`
`pip3 install requests`
