### ISSUE TITLE
Getting a infinitely repeating line after selecting college   

### ISSUE THREAD

**Issue by TTTT55** [KevinLage/Edu-Account-creator#37]
I'm getting this repeating line after selecting college: 

`message: Unable to find a matching set of capabilities `

**Comment by KevinLage** [comment]
make sure to use the latest version

**Comment by TTTT55** [comment]
Yup. Also,if I use it(.exe) on windows, it creates account on openccc apply page again and again. Can't pass through that page..

**Comment by KevinLage** [comment]
yeah fixed it in the .py version will release the exe later

**Comment by TTTT55** [comment]
Great

**Comment by KevinLage** [comment]
Done download the latest release

**Comment by TTTT55** [comment]
Alright. Thanks
