### ISSUE TITLE
Element not found

### ISSUE THREAD

**Issue by ajaikumarnadar** [KevinLage/Edu-Account-creator#42]
Message: Unable to locate element: [id="inputCollegeId"]

in 1st college

**Comment by ajaikumarnadar** [comment]
in 2nd attempt...

Message: Unable to locate element: [id="inputJUsername"]

**Comment by IT5-L0k35H** [comment]
Try to replace "inputJUsername" with "Username" in file Edu Bot.py by opening it in any other text editor like notepad++.
also replace "inputJPassword" with "Password".
*But first make a copy of this file

**Comment by LokeshK-Verma** [comment]
> Message: Unable to locate element: [id="inputCollegeId"]
*
*
Try to replace "inputJUsername" with "Username" in file Edu Bot.py by opening it in any other text editor like notepad++.
also replace "inputJPassword" with "Password".
*But first make a copy of this file

**Comment by KevinLage** [comment]
I wont fix it, maybe I will release an version without browser soon
