### ISSUE TITLE
Only Windows?

### ISSUE THREAD

**Issue by Shorty20** [KevinLage/Edu-Account-creator#48]
Hi,

when I run the script on my macOX I receive always this error

> [Errno 8] Exec format error: './geckodriver'

I guess its because if the geckodriver.exe and only windows works?

**Comment by KevinLage** [comment]
yeah there is no support for macOX

**Comment by KevinLage** [comment]
but it should work on linux and windows

**Comment by tarek369** [comment]
https://stackoverflow.com/questions/58053067/how-to-install-geckodriver-in-mac-terminal-permission-operation-not-permitted
