### ISSUE TITLE
[SUGGESTION] Ability to save SSN, DOB etc..

### ISSUE THREAD

**Issue by Nigel1992** [KevinLage/Edu-Account-creator#5]
Hello,

Thanks for your amazing script!
I do notice that some college's create a temp password  based upon your Dob [Date of Birth] or you use SSN to reset it.

Could you make it so it saves this info in the same output txt ?
I noticed it always uses March 7th, 1994 but when I use that for a temp password it says invalid so i don't know..

**Comment by KevinLage** [comment]
yeah its coming in the next update

**Comment by KevinLage** [comment]
added
