### ISSUE TITLE
Temp mail??

### ISSUE THREAD

**Issue by Kraaken132** [KevinLage/Edu-Account-creator#52]
How to open email to get edu accounts??
pl reply

**Comment by zeeha4043** [comment]
You can register at LACCD

Pada tanggal Sen, 11 Mei 2020 22.33, Kraaken132 <notifications@github.com>
menulis:

**Comment by 0m3rta13** [comment]
https://tempr.email/en/

Choose hartbot.de from dropdown. Get login from created eduaccounts.txt file in repo folder.
