### ISSUE TITLE
[Question] About gmail adresses

### ISSUE THREAD

**Issue by noesd** [KevinLage/Edu-Account-creator#55]
Hello.
I’d like to know if I can use one gmail address for multiple accounts ?
If not, can I use a mail forwarder ?

**Comment by KevinLage** [comment]
never tested if you can register with multiple account, but you can use an email forwarder

**Comment by Omargreen** [comment]
Thanks for your answer :)
edit : same person different account

**Comment by KevinLage** [comment]
np

**Comment by noesd** [comment]
It works !
