### ISSUE TITLE
[Request] Add manual input own email choice.

### ISSUE THREAD

**Issue by camlogical** [KevinLage/Edu-Account-creator#6]
Hello!

I found extra space in line 1549 (\n 8. Canada College\n 9. Santa Barbara\n\n").
It Should be \n8. Canada College\n9. Santa Barbara\n\n".

Request: Add manual input own email instead generate email with tempr.email.

**Comment by KevinLage** [comment]
I can add it in the next update

**Comment by camlogical** [comment]
after completed register for edu mail I just get a few welcome email (I used random tempr.email). I didn't get any important email (3 days until now.)

**Comment by KevinLage** [comment]
which college?

**Comment by zoe-barn** [comment]
Date if birth is required to login to account? 
What is the date of birth

**Comment by camlogical** [comment]
07-Mar-1994

**Comment by KevinLage** [comment]
thanks
