### ISSUE TITLE
Error: No module named 'requests'

### ISSUE THREAD

**Issue by supersri811** [KevinLage/Edu-Account-creator#60]
Traceback (most recent call last):
  File "Edu Bot.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

This is what I got while trying to generate a edu email. I followed all the instructions but still get the error. Can you fix this?

**Comment by KevinLage** [comment]
pip install requests
or
py -m pip install requests
or
python3 -m pip install requests

**Comment by supersri811** [comment]
Thanks a lot!
