### ISSUE TITLE
what are the default security questions Answers

### ISSUE THREAD

**Issue by cookiestart500** [KevinLage/Edu-Account-creator#68]
i need to answer 2 question for reset my password but i don't know what the bot has chosen

Question 1:
What school did you attend for sixth grade? 

 Question 2:
What is the first name of your least favorite relative?

![Create Password](https://user-images.githubusercontent.com/68061773/87034660-0ff59380-c19d-11ea-81f9-4fa57a14fddf.jpg)

**Comment by SerMax20** [comment]
its working?????

**Comment by MikeOwino** [comment]
the bot is supposed to do this for you

**Comment by MikeOwino** [comment]
> i need to answer 2 question for reset my password but i don't know what the bot has chosen
> 
> Question 1:
> What school did you attend for sixth grade?
> 
> Question 2:
> What is the first name of your least favorite relative?
> 
> ![Create Password](https://user-images.githubusercontent.com/68061773/87034660-0ff59380-c19d-11ea-81f9-4fa57a14fddf.jpg)

how did you get to that site it returns me to openccc site

**Comment by cookiestart500** [comment]
**i got to this site over the (Login)Hyperlink from the mail**

![mail](https://user-images.githubusercontent.com/68061773/87077896-aa26fd00-c1d8-11ea-9c95-6f4fb313cc04.jpg)




![01](https://user-images.githubusercontent.com/68061773/87077921-b4e19200-c1d8-11ea-98ee-a1244f3577e6.jpg)

**then i clicked on Expired/Forgotten Password**
![02](https://user-images.githubusercontent.com/68061773/87078245-31747080-c1d9-11ea-9e8d-c21823ad222c.jpg)

**after i enter my login id + captcha i get to the security question site (see picture in post 1)**

**But the problem is, I don't know the information. it is not in the txt files**
