### ISSUE TITLE
Throws Error after completing

### ISSUE THREAD

**Issue by domenicw1** [KevinLage/Edu-Account-creator#9]
Everything works but it errors after completing
```
[*] Page 3/3 Done!
[*] Sleeping 25 secounds!
1 / 1  Accounts are done!
C:\Users\AiS-9798\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe: Error while finding module specification for 'Edu Bot.py' (ModuleNotFoundError: __path__ attribute not found on 'Edu Bot' while trying to find 'Edu Bot.py')
```

**Comment by KevinLage** [comment]
Do u use the .exe or the .py?

**Comment by domenicw1** [comment]
I use .py

**Comment by KevinLage** [comment]
okay use the .exe https://github.com/KevinLage/Edu-Account-creator/releases/tag/1.2

**Comment by domenicw1** [comment]
that's not an exe

**Comment by KevinLage** [comment]
added a .exe version in releases

**Comment by camlogical** [comment]
I success create CCSF edu but there is no Google Drive. Screenshot: [http://prntscr.com/q3fvev](url)

**Comment by KevinLage** [comment]
I think they removed it because too many people abused it.

**Comment by camlogical** [comment]
> I think they removed it because too many people abused it.
I Hope not because of your tool. just kidding.
Please add more Colleges:
- Southwestern College (This is working with Google Drive)
- Mendocino College

I think Year of birth also effect to process of create edu account. Good year is 2001.
and please update season to spring 2020.

**Comment by KevinLage** [comment]
yeah gonna make a upadate soon

**Comment by camlogical** [comment]
Do you have any 2captcha api key?
